### ISSUE TITLE
Inaccurate Documentation

### ISSUE THREAD

**Issue by aseyfi** [PX4/PX4-containers#289]
Hello,

I was following the instructions in [this link](https://docs.px4.io/master/en/test_and_ci/docker.html#container-hierarchy). Looking at this table my understanding is that "px4-dev-ros" can do everything "px4-dev-nuttx" does, plus extra ROS and simulation applications, but it is not the case. "px4-dev-ros" doesn't include arm tool-chain and nuttx environment setup.

I am new to PX4 and Docker, so please forgive me, if this is a false alarm or this git repository is not the right place.

Thanks,
Ahmad

**Comment by hamishwillee** [comment]
Hi @aseyfi Thanks for posting.

This issue should be in the docs repo: https://github.com/PX4/PX4-user_guide

@TSC21 The table in https://docs.px4.io/master/en/test_and_ci/docker.html#container-hierarchy seems not to match well with https://github.com/PX4/PX4-containers#container-hierarchy
Any thoughts on what should be in the docs?

**Comment by TSC21** [comment]
> Hi @aseyfi Thanks for posting.
> 
> This issue should be in the docs repo: https://github.com/PX4/PX4-user_guide
> 
> @TSC21 The table in https://docs.px4.io/master/en/test_and_ci/docker.html#container-hierarchy seems not to match well with https://github.com/PX4/PX4-containers#container-hierarchy
> Any thoughts on what should be in the docs?

The docs needs to be in sync with what is in here or just be removed.

**Comment by hamishwillee** [comment]
Thanks. Fixed by https://github.com/PX4/PX4-user_guide/pull/1045
